<?php 
    $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8'); 
    $this->headTitle()->setSeparator(' - '); 
    $this->headTitle('Application'); 
    echo $this->doctype();
    //echo $_SERVER['DOCUMENT_ROOT'];
?> 

<html xmlns="http://www.w3.org/1999/xhtml">
	<head>    
		 <?php echo $this->headMeta(); ?>     
		 <?php echo $this->headTitle(); ?> 
		 <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/site.css'); ?>
		 <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
		  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
		 <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
		 <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/scripts/mindmup-editabletable.js"></script>
		 <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/scripts/table-sort.js"></script>
	</head> 
	<body> 
		<div id="content">    
			<h1><?php echo $this->escape($this->title); ?></h1>    
			<?php echo $this->layout()->content; ?> 
		</div> 
	</body> 
</html>